"""initial schema

Revision ID: dd992d75e43a
Revises: 
Create Date: 2026-04-02 14:47:08.524547
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dd992d75e43a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_job_titles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('apollo_person_id', sa.String(length=255), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agency_id', 'email', name='uq_contact_agency_email')
    )
    op.create_index(op.f('ix_contacts_agency_id'), 'contacts', ['agency_id'], unique=False)
    op.create_table('creators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instagram_handle', sa.String(length=255), nullable=True),
    sa.Column('tiktok_handle', sa.String(length=255), nullable=True),
    sa.Column('youtube_handle', sa.String(length=255), nullable=True),
    sa.Column('x_handle', sa.String(length=255), nullable=True),
    sa.Column('content_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('niche', sa.String(length=255), nullable=True),
    sa.Column('audience_size_approx', sa.String(length=100), nullable=True),
    sa.Column('media_kit_url', sa.String(length=500), nullable=True),
    sa.Column('media_kit_file_path', sa.String(length=500), nullable=True),
    sa.Column('bio_summary', sa.Text(), nullable=True),
    sa.Column('content_style', sa.Text(), nullable=True),
    sa.Column('audience_demographics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_descriptors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collaboration_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collaboration_verticals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_status', sa.String(length=50), nullable=False),
    sa.Column('profile_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_agency_id'), 'creators', ['agency_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('gmail_credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_agency_id'), 'users', ['agency_id'], unique=False)
    op.create_table('brand_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_domain', sa.String(length=255), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('apollo_organization_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scouting_status', sa.String(length=50), nullable=True),
    sa.Column('discovery_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_targets_agency_id'), 'brand_targets', ['agency_id'], unique=False)
    op.create_index(op.f('ix_brand_targets_creator_id'), 'brand_targets', ['creator_id'], unique=False)
    op.create_table('contact_associations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('brand_target_id', sa.UUID(), nullable=False),
    sa.Column('scouted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_target_id'], ['brand_targets.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'brand_target_id', name='uq_contact_brand_target')
    )
    op.create_index(op.f('ix_contact_associations_brand_target_id'), 'contact_associations', ['brand_target_id'], unique=False)
    op.create_index(op.f('ix_contact_associations_contact_id'), 'contact_associations', ['contact_id'], unique=False)
    op.create_table('outreach_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agency_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('brand_target_id', sa.UUID(), nullable=False),
    sa.Column('drafted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attach_media_kit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('gmail_draft_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['brand_target_id'], ['brand_targets.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['drafted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_emails_agency_id'), 'outreach_emails', ['agency_id'], unique=False)
    op.create_index(op.f('ix_outreach_emails_brand_target_id'), 'outreach_emails', ['brand_target_id'], unique=False)
    op.create_index(op.f('ix_outreach_emails_contact_id'), 'outreach_emails', ['contact_id'], unique=False)
    op.create_index(op.f('ix_outreach_emails_creator_id'), 'outreach_emails', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outreach_emails_creator_id'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_contact_id'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_brand_target_id'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_agency_id'), table_name='outreach_emails')
    op.drop_table('outreach_emails')
    op.drop_index(op.f('ix_contact_associations_contact_id'), table_name='contact_associations')
    op.drop_index(op.f('ix_contact_associations_brand_target_id'), table_name='contact_associations')
    op.drop_table('contact_associations')
    op.drop_index(op.f('ix_brand_targets_creator_id'), table_name='brand_targets')
    op.drop_index(op.f('ix_brand_targets_agency_id'), table_name='brand_targets')
    op.drop_table('brand_targets')
    op.drop_index(op.f('ix_users_agency_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_creators_agency_id'), table_name='creators')
    op.drop_table('creators')
    op.drop_index(op.f('ix_contacts_agency_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('agencies')
    # ### end Alembic commands ###
